### PR TITLE
Fix build on Linux

### PR DESCRIPTION
**Pull request by avsej**
Mostly fixing filenames for case-sensitive file systems and converting
C# 7 syntax for accessors to more concise form (which is also portable).

### CODE REVIEW

**Comment by wisestump** [comment]
Why do you want to remove C# 7.0 features if Mono compiler supports them? [Documentation page](http://www.mono-project.com/docs/about-mono/languages/csharp/) says that simple forms of pattern matching and expression-bodied accessors are supported.

**Comment by avsej** [comment]
on the most recent fedora these features are not available.  how those accessors better than regular?

**Comment by wisestump** [comment]
Development team decided to upgrade project to the latest available compiler/IDE version and use it's features. Unfortunatelly fedora didn't yet update mono compiler, so you have either to wait for an update or use different Linux distribution (e.g. Ubuntu)

**Comment by avsej** [comment]
but why those new non-portable accessors better than older ones? Do the generate faster code or something?

**Comment by wisestump** [comment]
They are portable in terms of C# compiler and they are more convenient. If you don't need the latest features of PascalABC.NET you can build an older version, which is compatible with your compiler. In the other case you have to find a way to build the project using the latest available mono compiler.

**Comment by ulysses4ever** [comment]
@wisestump I added a label `wontfix` and suggest closing the PR.

**Pull request closed without merging**
