### PR TITLE
Compiler: preload the reference assemblies, add an assembly resolver

### PR DESCRIPTION
**Pull request by ForNeVeR**
So, [as I said in the discussion list](https://github.com/pascalabcnet/pascalabcnet/discussions/2709), I'm working on PascalABC.NET SDK for MSBuild, which will allow to (optionally!) bring modern .NET development practices to the ecosystem of this wonderful language.

One particular challenge I am struggling to solve is to allow the compiler to use NuGet packages. As a first sample, I took a (nontrivial) project [showing the AvaloniaUI usage in PascalABC.NET](https://github.com/ForNeVeR/avalonia-pascalabc-net-showcase).

The project has 129 (!) assembly references provided by the AvaloniaUI and default .NET Framework SDK.

All of the assemblies in question live in different directories (since they are placed in the NuGet cache or GAC initially), and they have various interesting dependency issues: some of them are mutually-dependent (an infamous case of this is `System` depending on `System.Xml`, and `System.Xml` depending on `System`). This causes issues when the compiler tries to load and enumerate types in an assembly which depends on another one (not loaded yet).

Another problem is that the assembly references in .NET are versioned, and yet NuGet doesn't follow the references strictly. Say, if you have a reference on assembly version 3.0.0, NuGet may happily provide you with an assembly version 3.0.100. By default, .NET Framework will fail to look up such a reference and the compiler will break.

In this PR, I've resolved both problems by:
- adding an assembly preload stage (which does only assembly loading and doesn't try to load any types from them), and
- adding an additional scoped handler for `AppDomain::AssemblyResolve` event that forces the runtime to load the user-requested references strictly (ignoring the versioning issues).

Some comments:
1. I'm not sure about adding the `overwrite` flag to `GetReferenceFileName`. The current method implementation doesn't look good to me, since it doesn't only get the name, but also copies the file sometimes, but I'm not sure if we want to redesign it in the scope of this task. This method is now called twice for each reference: the first time on assembly preload, and the second time on reference compilation; without the flag, it will copy the same assembly for the second time which is suboptimal.
2. I'm not sure the `try…catch` block around the `PreloadAssembly` call in `NetHelper::LoadAssembly` is required after this fix. It looks like it was solving the same task as my PR.
3. Also, there's another handler for `AppDomain::AssemblyResolve` added here: https://github.com/pascalabcnet/pascalabcnet/blob/198faa5bf5e4298560edb2e1c87adec354ad0191/TreeConverter/NetWrappers/NetHelper.cs#L927
   I believe we can remove that one, too, but it requires some additional testing of course.
4. Note that earlier, there was a call to `Assembly::GetTypes` in `NetHelper`, inside of a block I have replaced with `PreloadAssembly`. `Assembly::GetTypes` gets called on compilation anyway, so I've decided to optimize that out. Please help me to validate this decision.

This change is pretty important, because it will unblock me to release a new version of PascalABC.NET SDK with full NuGet support for .NET Framework (and this, in turn, will open a road for more projects in PascalABC.NET, and more ways to use the compiler for all people).

### CODE REVIEW

**Comment by SunSerega** [comment]
> The current method implementation doesn't look good to me, since it doesn't only get the name, but also copies the file sometimes

Yes, the copy is important but misplaced after your changes. It makes more sense to copy all .dll to the .exe folder when enumerating them in preload stage.
And I think (not sure) there also was a problem that indirect references were not copied... With everything being preloaded this should also be fixed.

That was for a part I wrote. Can't be so sure about everything else, but I think you should try removing the rest of the old ugly solutions you mentioned and see if anything in `_GenerateAllSetups.bat` breaks. From a quick look, I can't see any non-trivial issues that can arise and can't be tested for automatically.

**Comment by ForNeVeR** [comment]
> Yes, the copy is important but misplaced after your changes. It makes more sense to copy all .dll to the .exe folder when enumerating them in preload stage.

Ah, thanks for the suggestion, I think you're correct.

In my local experiments, the DLLs were already copied to the target directory, that's why I didn't notice the issue with this code. I'll fix it.

> And I think (not sure) there also was a problem that indirect references were not copied...

This is still a problem with the current approach. We only copy the direct references, and currently everything else is on the user.

PascalABC.NET SDK resolves this problem by adding everything to the references transitively, and I believe it is a good approach. Even if we aren't talking about the SDK, this shouldn't be the task of this part of the compiler, and generally it's impossible to solve in the compiler alone (because of how NuGet works, and I strongly believe this is a good model we should keep our code in line to).

**Comment by ForNeVeR** [comment]
> Can't be so sure about everything else, but I think you should try removing the rest of the old ugly solutions you mentioned 

I would vote for merging this initial part first, and then working on a bigger refactoring and removing the old workarounds. Assembly resolve is a tricky part, and we should step carefully.

I'm ready to work on that refactoring after this PR gets merged, though.

**Comment by SunSerega** [comment]
> PascalABC.NET SDK resolves this problem by adding everything to the references transitively, and I believe it is a good approach

Well, yes, it is... However, there is another competing model already in place. When you add a module to `uses` - it automatically caries every resource (`$resource`, `$include`, other `uses`, etc.) it requires to either the resulting assembly (if it's code or `$resource`) or the output directory (like in case of .dll).
It is even more relevant after I implemented the current `uses-in` system, where modules in the different folders will look for resources in their own folders.
This module allows modules to not have a strong binding to the folder of the main module file. It is important because this way the modules are more modular.

If the .dll is referenced as a global setting, used for the whole compilation (like in the file for MSBuild) - it's fine if the compiler isn't responsible for indirectly referenced .dll files.

But if .dll is referenced in a pascal module file - the compiler needs to resolve everything and be sure that all resources would be accessible during execution, no matter the level of indirection.

---

As a middle ground, maybe it would make sense to create a compiler argument for adding an external program, like NuGet, as a library resolver.
So far, when adding external libraries, I put them into a separate folder (with their license, etc.), like [here](https://github.com/SunSerega/POCGL/tree/stable/Packing/Reference/!MarkDig). But of course, with such an approach, I can't even automatically update dependencies.

**Comment by ForNeVeR** [comment]
> Yes, the copy is important but misplaced after your changes. It makes more sense to copy all .dll to the .exe folder when enumerating them in preload stage.

After a new review, I found that everything works correctly (at least I think so): the assemblies get copied on preloading.

**Comment by ForNeVeR** [comment]
> But if .dll is referenced in a pascal module file - the compiler needs to resolve everything and be sure that all resources would be accessible during execution, no matter the level of indirection.

As far as I can see, this already works correctly (in a sense, at least): all the references from a module get translated to the main assembly as well.

> As a middle ground, maybe it would make sense to create a compiler argument for adding an external program, like NuGet, as a library resolver.

The MSBuild SDK I'm working on resolves this by generating a new module populated by all the project references. The user is then expected to add `uses References_Generated` to their Pascal modules.

**Comment by ForNeVeR** [comment]
FYI, at least the test step on GitHub Actions [is all green](https://github.com/ForNeVeR/pascalabcnet/actions/runs/3123062439/jobs/5065431342) in this branch of my fork.

**Comment by ForNeVeR** [comment]
For the record: the currently unresolved problem is that a project using Microsoft.ML NuGet package cannot be compiled by the IDE from this branch, while the main branch compiles it fine.
```pascal
{$reference Microsoft.ML.Core.dll}
{$reference Microsoft.ML.Data.dll}
{$reference Microsoft.ML.DataView.dll}
{$reference Microsoft.ML.KMeansClustering.dll}

uses Microsoft.ML;
uses Microsoft.ML.Data;
uses Microsoft.ML.Trainers;
uses Microsoft.ML.Transforms;
 
// Описание необходимых типов 
type 
  IrisData = auto class
  public
    &Label: single; 
    SepalLength: single; 
    SepalWidth: single; 
    PetalLength: single; 
    PetalWidth: single;
  end; 

  IrisPrediction = class
    public 
    [ColumnName('PredictedLabel')]
    SelectedClusterId: longword; 

    [ColumnName('Score')]
    Distances: array of single;
  end;
 
begin
  // Создание контекста
  var Context := new MLContext();
  // Считывание значений из файла
  var fullData := Context.Data.LoadFromTextFile('T:\Temp\iris-full.txt',
    Arr(
      new TextLoader.Column('Label', DataKind.Single, 0),
      new TextLoader.Column('SepalLength', DataKind.Single, 1),
      new TextLoader.Column('SepalWidth', DataKind.Single, 2),
      new TextLoader.Column('PetalLength', DataKind.Single, 3),
      new TextLoader.Column('PetalWidth', DataKind.Single, 4)
    ),
    #9, True
  );
  // Разбиение на тренировочную и тестовую выборки
  var trainTestData := Context.Data.TrainTestSplit(fullData, 0.2);
  var trainingDataView := trainTestData.TrainSet;
  var testingDataView := trainTestData.TestSet;
  
  // Формирование пайплайна - не знаю, что такое. Видимо, последовательность вычислений
  var trainingPipeline := 
    Context.Transforms.Concatenate('Features','SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth')
    .Append(Context.Clustering.Trainers.KMeans('Features', nil, 3));
  
  // Тренировка модели по тренировочным данным
  var model := trainingPipeline.Fit(trainingDataView);
  
  // Проверка модели на тестовых данных и вывод метрик полученной модели
  var predictions := model.Transform(testingDataView);
  var metrics := Context.Clustering.Evaluate(predictions, nil, 'Score', 'Features');
  Println(metrics.DaviesBouldinIndex);

  // Предсказание кластера для конкретного данного
  // Данное
  var sampleIrisData := new IrisData(0,3.3,1.6,0.2,5.1);
  // Создание предсказывающей машины
  var predictor := Context.Model.CreatePredictionEngine&<IrisData, IrisPrediction>(model);
  // Запуск предсказывающей машины на указанном данном
  var resultprediction := predictor.Predict(sampleIrisData);
  Print(resultprediction.SelectedClusterId);
end.
```

I've fixed the project loading problem in the IDE, but still struggle with compiling it properly. Right now, the compiler complains it cannot find the `KMeans` method.

**Pull request merged**
